name: hire_test
version: 1.0.0+1
publish_to: none
description: Hire test project
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  dio: ^5.3.2
  velocity_x: ^3.6.0
  get_storage: ^2.1.1
  another_flushbar: ^1.12.30
  email_validator: ^2.1.17
  google_fonts: ^4.0.4
  progress_dialog_null_safe: ^1.0.7

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

get_cli:
  sub_folder: false